[project]
name = "video-feed-stub"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "numpy<2",
    "opencv-python>=4.11.0.86",
    "pyfakewebcam>=0.1.0",
]
